src/components/ActivityMap/ActivityStats.tsx, src/models/garminActivity.ts, src/storage/garminActivityLocalStorage.ts, src/utils/distanceUtils.ts, src/utils/garminUtils.ts
=> add max pace

src/components/MapboxMap/MapboxMap.tsx
=> Fullscreen

src/components/ActivityMap/AltitudeChart.tsx, src/storage/garminActivityLocalStorage.ts, src/utils/garminUtils.ts
newer watches only have enhancedaltitude
=> newer watches only have enhancedaltitude

src/components/ActivityMap/AltitudeChart.tsx, src/components/ActivityMap/AltitudeMap.tsx
Turns out black on black is hard to read
=> fixes dark mode colors

src/components/MapboxMap/MapboxMap.tsx, src/contexts/UserPreferencesContext.tsx, src/models/userPreferences.ts, src/pages/_app.tsx, src/storage/userPreferencesLocalStorage.ts
- Creates user preferences in local storage
- Adds map theme to it
=> Map theme stored in user preferences

src/components/Collapse/Collapse.tsx, src/components/GarminUploadInstructions/GarminUploadInstructions.tsx
Background occasionally was the wrong light/dark color. Outlining simplifies this a lot.
=> Fixed bad background

src/components/ActivityMap/AltitudeMap.tsx, src/pages/p/strava-activities/index.tsx
Closes #88 
Ties the altitude map based on wall-clock time, not index alignment.
=> fix altitude map

src/components/ActivityMap/ActivityStats.tsx
=> two column layout for stats

package-lock.json, package.json
Patches high-sev CSRF vulnerability
=> bump next-auth

src/components/ActivityMap/AltitudeChart.tsx, src/components/ActivityMap/AltitudeMap.tsx
I think this is a more elegant solution than filtering out incomplete data points.
=> plot nulls

src/components/ActivityMap/ActivityStats.tsx, src/utils/distanceUtils.ts
Would close #59
These work by computing discrete acceleration values between pairs of velocity calculations (which themselves are discrete approximations), then retaining either the max (fastest accel) or the min (hardest decel)
=> add max accel and decel

src/components/Collapse/Collapse.tsx, src/components/FullPageLoader/FullPageLoader.tsx, src/components/GarminFilePicker/GarminFilePicker.tsx, src/components/GarminUploadInstructions/GarminUploadInstructions.tsx, src/components/Pagination/LoadingIndicator.tsx, src/components/StravaActivityCard/StravaActivityCard.tsx
Lighthouse brought up some areas we weren't accessible
=> resolve accessibility issues

src/apiClients/stravaClient/converters.ts, src/utils/distanceUtils.test.ts, src/utils/distanceUtils.ts, src/utils/garminUtils.test.ts, src/utils/garminUtils.ts
Filters out impossible data points
=> remove bogus data

src/colors.ts, src/components/ActivityMap/DetailedActivityMapBase.tsx, src/components/ActivityMap/DetailedActivityMapWithGarmin.tsx, src/components/ActivityMap/Legend.tsx, src/components/ActivityMap/MapMarker.tsx
Customer made some requests:
- replace emojis with dots
- make the lines the same width
- center the dots on the lines
=> replace emojis

package-lock.json, package.json, src/hooks/useInfiniteScroll.ts, src/hooks/useIsVisible.ts, src/pages/p/strava-activities/buildActivityPairs.ts, src/pages/p/strava-activities/fetchMore.ts, src/pages/p/strava-activities/getActivityDistance.ts, src/pages/p/strava-activities/index.tsx
Our main page was getting pretty cluttered, this just pulls out functions to their own files for housekeeping
=> refactor: extract business logic

src/components/ActivityMap/ActivityStats.tsx, src/components/ActivityMap/Legend.tsx
Hide the legend entry and average if no zoomies
=> only show zoomies if present

src/components/StoredActivityIndicator/StoredActivityIndicator.tsx, src/pages/p/strava-activities/index.tsx, src/utils/uniqueBy.ts
Uniques activities, mainly for the test data case, but also helps if new activities are ever injected between pages. Fixes pluralization typo.
=> unique results

src/components/ActivityMap/AltitudeChart.tsx, src/components/Collapse/Collapse.tsx, src/components/GarminFilePicker/GarminFilePicker.tsx, src/components/GarminFilePicker/GarminFilePickerContainer.tsx, src/components/GarminUploadInstructions/GarminUploadInstructions.tsx, src/components/GarminUploadSection/GarminUploadSection.tsx, src/components/MapboxMap/MapboxMap.tsx, src/components/StoredActivityIndicator/StoredActivityIndicator.tsx, src/hooks/useDisplayIsSizeOrLarger.ts, src/layout/Header/Header.tsx, src/pages/p/activity/[stravaActivityId].tsx, src/pages/p/strava-activities/index.tsx
Our app looks bad on mobile. Not a big deal since upload from those devices isn't very likely, but no reason to look bad IMO.
**Current Production**
**This Branch**
=> Mobile Friendly

src/components/ActivityMap/ActivityStats/useActivityStatsRows.ts
I accidentally removed it here: https://github.com/aradmargalit/milameter/pull/121/files#diff-8184ff9c85b1db403416c2543cd4c03c4d4a899801a64dd96056bb8b03435b6bL140-L149
Adding it back in this PR
=> Adds Max Separation

src/components/ActivityMap/ActivityStats/ActivityStatRow.tsx, src/components/ActivityMap/ActivityStats/useActivityStatsRows.ts, src/components/ActivityMap/DetailedActivityMapBase.tsx, src/components/ActivityMap/DetailedActivityMapWithGarmin.tsx, src/components/ActivityMap/Legend.tsx, src/components/ActivityMap/MaxSeparationLine.tsx, src/contexts/ActivityPairContext/derivedActivityProperties.ts, src/contexts/MapContext.tsx, src/pages/_app.tsx, src/utils/distanceUtils.ts
=> show max sep on map

src/components/ActivityGrid/ActivityGrid.tsx
Closes #140 
https://github.com/user-attachments/assets/7472f09c-6be2-4dfd-80c4-935dbaf19a77
=> add more columns for wider displays

src/components/MapboxMap/MapboxMap.tsx, src/contexts/MapContext.tsx, src/pages/p/activity/[stravaActivityId].tsx
=> progress towards fullscreen

src/components/ActivityMap/ActivityStats/useActivityStatsRows.ts
=> total zoomies

src/components/MapboxMap/MapboxMap.tsx, src/components/pages/activity/DetailedActivityMap.tsx
Removes an unused height prop and makes the actually used one dynamic.
=> fixes map height

package-lock.json, package.json, src/components/ActivityMap/AltitudeChart.tsx, src/components/ActivityMap/AltitudeMap.tsx, src/components/ActivityMap/hooks/useDragZoom.ts
- Switches to Area Chart for #beauty
- Closes #91 
- Lets the user zoom into a specific section of the altitude map and zoom back out
- 
https://github.com/user-attachments/assets/e929931c-4569-4a0c-bebd-2f0e14cf6c8a
=> Better Altitude Map

src/components/pages/strava-activities/buildActivityPairs.ts, src/pages/p/strava-activities/index.tsx
Sometimes garmin activities have no records, as is the problem here: https://arad-margalit.sentry.io/issues/6681660627/?project=4504714643111936&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
=> hotfix for bad GPX
